<a href="https://colab.research.google.com/github/itshemanthcode/Project-SkillMatch-Resume-Matcher-and-Skill-Recommender/blob/main/Numerical_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
import numpy as np
n1=np.full((3,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
import numpy as np
# Corrected the function name from 'np.zeroes' to 'np.zeros'
n1 = np.zeros((1, 2))
print(n1)

[[0. 0.]]


In [ ]:
import numpy as np
# Corrected the function name from 'np.zeroes' to 'np.zeros'
n1 = np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
# Corrected the function name from 'np.zeroes' to 'np.zeros'
n1 = np.arange(1,100,3)
n1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
import numpy as np
# Corrected the function name from 'np.zeroes' to 'np.zeros'
n1 = np.random.randint(1,100,5)
n1

array([73, 48, 21, 44, 91])

In [ ]:
import numpy as np
n1= np.array([[10,200,4,30],[50,6,20,70]])
n1.shape

(2, 4)

In [ ]:
import numpy as np
# Corrected the function name from 'np.zeroes' to 'np.zeros'
n1 = np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n2= np.array([50,60,70,90])
np.vstack((n1,n2))

array([[10, 20, 30, 40],
       [50, 60, 70, 90]])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n2= np.array([50,60,70,90])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60, 70, 90])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n2= np.array([50,60,70,90])
np.column_stack((n1,n2))

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 90]])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40,50,60])
n2= np.array([50,60,70,90])

In [ ]:
np.intersect1d(n1,n2)

array([50, 60])

In [ ]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [ ]:
np.setdiff1d(n2,n1)

array([70, 90])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n2= np.array([50,60,70,90])
np.sum([n1,n2])

np.int64(370)

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n2= np.array([50,60,70,90])
np.sum([n1,n2],axis=0)

array([ 60,  80, 100, 130])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n2= np.array([50,60,70,90])
np.sum([n1,n2],axis=1)

array([100, 270])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n1=n1*2
n1

array([20, 40, 60, 80])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n1=n1+2
n1

array([12, 22, 32, 42])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n1=n1/2
n1

array([ 5., 10., 15., 20.])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
n1=n1-2
n1

array([ 8, 18, 28, 38])

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
np.mean(n1)

np.float64(25.0)

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
np.std(n1)

np.float64(11.180339887498949)

In [ ]:
import numpy as np
n1= np.array([10,20,30,40])
np.median(n1)

np.float64(25.0)

In [ ]:
import numpy as np
# Added a comma after the second list
n1 = np.array([[10, 200, 4, 30], [50, 6, 20, 70], [20, 33, 1, 3]])
n1

array([[ 10, 200,   4,  30],
       [ 50,   6,  20,  70],
       [ 20,  33,   1,   3]])

In [ ]:
import numpy as np
n1= np.array([[10,200,4,30], [50,6,20,70],[20,33,1,3]])
n1.transpose()

array([[ 10,  50,  20],
       [200,   6,  33],
       [  4,  20,   1],
       [ 30,  70,   3]])

In [ ]:
import numpy as np
n1= np.array([[10,20,4,30], [50,6,20,70],[20,33,1,3]])
n1

array([[10, 20,  4, 30],
       [50,  6, 20, 70],
       [20, 33,  1,  3]])

In [ ]:
import numpy as np
n2= np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
n2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])